//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMIR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASCodeTableDetail
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public string LngNo { get; set; }
        public string TypeNo { get; set; }
        public string KeyNo { get; set; }
        public string Descr { get; set; }
        public string Descr2 { get; set; }
        public string Attribute01 { get; set; }
        public string Attribute02 { get; set; }
        public string Attribute03 { get; set; }
        public string Attribute04 { get; set; }
        public string Attribute05 { get; set; }
        public string Attribute06 { get; set; }
        public string AttributeDesp { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public int OrderSR { get; set; }
        public string AddUserNo { get; set; }
        public string AddUserName { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string ModifyUserNo { get; set; }
        public string ModifyUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string IPAddress { get; set; }
    
        public virtual BASCodeTableMaster BASCodeTableMaster { get; set; }
    }
}
