//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMIR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASCodeTableMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BASCodeTableMaster()
        {
            this.BASCodeTableDetail = new HashSet<BASCodeTableDetail>();
        }
    
        public int Id { get; set; }
        public string TypeNo { get; set; }
        public string TypeDescr { get; set; }
        public int KeyNoLength { get; set; }
        public bool IsSyncViaSap { get; set; }
        public string AddUserNo { get; set; }
        public string AddUserName { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string ModifyUserNo { get; set; }
        public string ModifyUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string IPAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BASCodeTableDetail> BASCodeTableDetail { get; set; }
    }
}
