//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMIR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IRFEntities : DbContext
    {
        public IRFEntities()
            : base("name=IRFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BASCodeTableDetail> BASCodeTableDetail { get; set; }
        public virtual DbSet<BASCodeTableMaster> BASCodeTableMaster { get; set; }
        public virtual DbSet<IRF030> IRF030 { get; set; }
        public virtual DbSet<ODF100> ODF100 { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<WebSite> WebSite { get; set; }
        public virtual DbSet<WebSiteType> WebSiteType { get; set; }
        public virtual DbSet<WebUserInfo> WebUserInfo { get; set; }
        public virtual DbSet<WebUserPage> WebUserPage { get; set; }
        public virtual DbSet<WebUserPermission> WebUserPermission { get; set; }
        public virtual DbSet<WebUserTab> WebUserTab { get; set; }
        public virtual DbSet<WebUserType> WebUserType { get; set; }
    }
}
