//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMIR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IRFEntities : DbContext
    {
        public IRFEntities()
            : base("name=IRFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<ATTRDL> ATTRDL { get; set; }
        public virtual DbSet<ATTRMT> ATTRMT { get; set; }
        public virtual DbSet<BASCodeTableDetail> BASCodeTableDetail { get; set; }
        public virtual DbSet<BASCodeTableMaster> BASCodeTableMaster { get; set; }
        public virtual DbSet<GRPNO> GRPNO { get; set; }
        public virtual DbSet<GRPPMS> GRPPMS { get; set; }
        public virtual DbSet<IRF030> IRF030 { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<ODF100> ODF100 { get; set; }
        public virtual DbSet<PRGNO> PRGNO { get; set; }
        public virtual DbSet<SYSBLOB> SYSBLOB { get; set; }
        public virtual DbSet<SYSCONFG> SYSCONFG { get; set; }
        public virtual DbSet<SYSNO> SYSNO { get; set; }
        public virtual DbSet<USRGRP> USRGRP { get; set; }
        public virtual DbSet<USRNO> USRNO { get; set; }
        public virtual DbSet<USRPMS> USRPMS { get; set; }
        public virtual DbSet<vw_MENU> vw_MENU { get; set; }
        public virtual DbSet<vw_PRGNO> vw_PRGNO { get; set; }
        public virtual DbSet<vw_System_Program> vw_System_Program { get; set; }
        public virtual DbSet<vw_System_Program_Menu> vw_System_Program_Menu { get; set; }
        public virtual DbSet<vw_System_Program_Menu_GROUP> vw_System_Program_Menu_GROUP { get; set; }
        public virtual DbSet<vw_System_Program_Menu_USER> vw_System_Program_Menu_USER { get; set; }
        public virtual DbSet<vw_System_Program_Menu_USER_PMS> vw_System_Program_Menu_USER_PMS { get; set; }
    }
}
