//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMIR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRF030
    {
        public int Id { get; set; }
        public string SYS_NO { get; set; }
        public string DOOR { get; set; }
        public Nullable<decimal> DOOR_POINT { get; set; }
        public string W_STN { get; set; }
        public Nullable<decimal> PLAN_W { get; set; }
        public Nullable<decimal> IR_ROUND { get; set; }
        public Nullable<decimal> SYS45_LOSS { get; set; }
        public Nullable<decimal> IR_W1_1 { get; set; }
        public Nullable<decimal> IR_W1_2 { get; set; }
        public Nullable<decimal> IR_W2 { get; set; }
        public Nullable<decimal> IR_W3 { get; set; }
        public Nullable<decimal> DRY { get; set; }
        public Nullable<decimal> RAIN_1 { get; set; }
        public Nullable<decimal> RAIN_2 { get; set; }
        public Nullable<decimal> RAIN_3 { get; set; }
        public Nullable<decimal> RAIN_4 { get; set; }
        public Nullable<decimal> RAIN_5 { get; set; }
        public Nullable<decimal> RAIN_6 { get; set; }
        public Nullable<decimal> RAIN_7 { get; set; }
        public Nullable<decimal> RAIN_8 { get; set; }
        public Nullable<decimal> RAIN_9 { get; set; }
        public Nullable<decimal> RAIN_10 { get; set; }
        public Nullable<decimal> RAIN_11 { get; set; }
        public Nullable<decimal> RAIN_12 { get; set; }
        public string SOIL { get; set; }
        public Nullable<decimal> POINT_LOSS { get; set; }
        public Nullable<decimal> DRY1 { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public string modify_user_id { get; set; }
        public Nullable<System.DateTime> modify_datetime { get; set; }
    }
}
