//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMIR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRGNO
    {
        public System.Guid ID { get; set; }
        public string PRG_NO { get; set; }
        public string PRG_NM { get; set; }
        public string SYS_NO { get; set; }
        public string PRG_TY { get; set; }
        public string PRG_URL1 { get; set; }
        public string PRG_URL2 { get; set; }
        public Nullable<int> PRG_SR { get; set; }
        public string C_RUN { get; set; }
        public string C_ADD { get; set; }
        public string C_QRY { get; set; }
        public string C_MDY { get; set; }
        public string C_CFM { get; set; }
        public string C_UCF { get; set; }
        public string C_DEL { get; set; }
        public string C_CST { get; set; }
        public string C_CPY { get; set; }
        public string C_EML { get; set; }
        public string C_ATT { get; set; }
        public string C_SIN { get; set; }
        public string OWNER_USR_NO { get; set; }
        public string OWNER_GRP_NO { get; set; }
        public Nullable<System.DateTime> ADD_DT { get; set; }
        public string MDY_USR_NO { get; set; }
        public Nullable<System.DateTime> MDY_DT { get; set; }
        public string IP_NM { get; set; }
        public string CP_NM { get; set; }
    }
}
