//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMIR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSBLOB
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public byte[] FileContent { get; set; }
        public string FileType { get; set; }
        public Nullable<int> FileLength { get; set; }
        public string GUID { get; set; }
        public string FileExtName { get; set; }
        public string Path { get; set; }
        public string FullPath { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastWriteTime { get; set; }
        public string AddUserNo { get; set; }
        public string AddUserName { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string ModifyUserNo { get; set; }
        public string ModifyUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string IPAddress { get; set; }
    }
}
