//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMIR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSCONFG
    {
        public System.Guid ID { get; set; }
        public string ROW_NO { get; set; }
        public string CURR_YM { get; set; }
        public Nullable<System.DateTime> CLS_DT { get; set; }
        public string CURRENCY { get; set; }
        public string IVC_PAGE { get; set; }
        public string TAX_TY { get; set; }
        public Nullable<decimal> TAX_RT { get; set; }
        public Nullable<int> ACT_CURR_YY { get; set; }
        public Nullable<System.DateTime> ACT_CLS_DT { get; set; }
        public string PR_ACT_NO { get; set; }
        public string IN_ACT_NO { get; set; }
        public string OT_ACT_NO { get; set; }
        public string AP_ACT_NO { get; set; }
        public string NP_ACT_NO { get; set; }
        public string AR_ACT_NO { get; set; }
        public string NR_ACT_NO { get; set; }
        public string DS_ACT_NO { get; set; }
        public string DR_ACT_NO { get; set; }
        public string EAR_DIFF_ACT_NO { get; set; }
        public string SLY_NP_ACT_NO { get; set; }
        public string SLY_CASH_ACT_NO { get; set; }
        public string RAR_TY { get; set; }
        public string R_ACT_NO { get; set; }
        public string R_BCH_NO { get; set; }
        public string R_BANK_NO { get; set; }
        public string OWNER_USR_NO { get; set; }
        public string OWNER_GRP_NO { get; set; }
        public Nullable<System.DateTime> ADD_DT { get; set; }
        public string MDY_USR_NO { get; set; }
        public Nullable<System.DateTime> MDY_DT { get; set; }
        public string IP_NM { get; set; }
        public string CP_NM { get; set; }
    }
}
