//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMIR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.WebUserType1 = new HashSet<WebUserType>();
            this.WebUserType2 = new HashSet<WebUserType>();
        }
    
        public int UserInfo_NO { get; set; }
        public string UserInfo_Id { get; set; }
        public int UserInfo_Rcd { get; set; }
        public string UserInfo_AD { get; set; }
        public string UserInfo_PWD { get; set; }
        public string UserInfo_Email { get; set; }
        public string UserInfo_Phone { get; set; }
        public string UserInfo_Name { get; set; }
        public int UserInfo_AppType { get; set; }
        public int UserInfo_WebType { get; set; }
        public string UserInfo_NationalId { get; set; }
        public string UserInfo_TwTitle { get; set; }
        public bool UserInfo_IsSignException { get; set; }
        public bool UserInfo_IsGiftException { get; set; }
        public bool UserInfo_IsEnabled { get; set; }
        public int UserInfo_APPUIId { get; set; }
        public int UserInfo_WebUIId { get; set; }
        public System.DateTime UserInfo_ModifyTime { get; set; }
        public System.DateTime UserInfo_CreateTime { get; set; }
    
        public virtual WebUserInfo WebUserInfo { get; set; }
        public virtual WebUserType WebUserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebUserType> WebUserType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebUserType> WebUserType2 { get; set; }
    }
}
