//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMIR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_System_Program
    {
        public System.Guid ID { get; set; }
        public string SYSNO { get; set; }
        public string SYSNO_NAME { get; set; }
        public string Kind_Name { get; set; }
        public string PRGNO { get; set; }
        public string PROGRAMNO_NAME { get; set; }
        public string PROG_URL1 { get; set; }
        public string PROG_URL2 { get; set; }
        public int SYSTEMNO_ORDERID { get; set; }
        public System.Guid SYS_SYSTEMNO_Id { get; set; }
        public string BASCodeTableDetail_OrderSR { get; set; }
        public System.Guid BASCodeTableDetail_Id { get; set; }
        public int PROGRAMNO_ORDERID { get; set; }
        public System.Guid PROGRAMNO_Id { get; set; }
        public string emp_no { get; set; }
        public Nullable<int> SYS_SR { get; set; }
        public string SYS_CLASS { get; set; }
    }
}
