//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMIR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebUserPermission
    {
        public int WUPermission_Id { get; set; }
        public int WUPermission_WUType_Id { get; set; }
        public int WUPermission_WUTab_Id { get; set; }
        public int WUPermission_WUPage_Id { get; set; }
        public bool WUPermission_IsEnabled { get; set; }
    
        public virtual WebUserType WebUserType { get; set; }
    }
}
