//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMIR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebUserType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebUserType()
        {
            this.UserInfo = new HashSet<UserInfo>();
            this.WebUserPermission = new HashSet<WebUserPermission>();
        }
    
        public int WUType_Id { get; set; }
        public string WUType_Name { get; set; }
        public string Note { get; set; }
        public bool WUType_IsEnabled { get; set; }
        public int WUType_ModifyUser { get; set; }
        public int WUType_CreateUser { get; set; }
        public System.DateTime WUType_ModifyTime { get; set; }
        public System.DateTime WUType_CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInfo> UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
        public virtual UserInfo UserInfo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebUserPermission> WebUserPermission { get; set; }
    }
}
