<?xml version="1.0" encoding="utf-8"?><Database Class="IRF_DBContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=OPALAVENGER-PC\MSSQL2012;Initial Catalog=IRF;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="IRFDBConnectionString" Provider="System.Data.SqlClient" />
</Database>